### ISSUE TITLE
it‘s no effect

### ISSUE THREAD

**Issue by Yh1404** [alloc/vite-plugin-compress#16]
befor use this plugin
<img width="672" alt="image" src="https://user-images.githubusercontent.com/39335644/174033763-2bdedd31-35ea-43bb-964a-13aa2b375eb3.png">
after
<img width="623" alt="image" src="https://user-images.githubusercontent.com/39335644/174033977-4733a7b8-dfb5-4f83-b84e-f7f330c1c497.png">
the `.jpg` file didn't compressed at all.

**Comment by Yh1404** [comment]
this is my  config
<img width="607" alt="image" src="https://user-images.githubusercontent.com/39335644/174034262-f09374fa-1dd7-4461-a740-5753a1d87d95.png">

**Comment by aleclarson** [comment]
Picture formats are already optimized. You can't compress them further without losing image quality.

**Comment by aleclarson** [comment]
Also, only png and webp are currently supported for lossy compression

**Comment by Yh1404** [comment]
> Also, only png and webp are currently supported for lossy compression
i get it, thanks for u reply
