### ISSUE TITLE
viteCompress is not a function

### ISSUE THREAD

**Issue by acalvino4** [alloc/vite-plugin-compress#17]
I have the basic setup that the README documents;
```ts
import viteCompress from 'vite-plugin-compress'
...
export default defineConfig(({ command }) => ({
  ...
  plugins: [
    viteCompress(),
  ]
  ...
}
```
But I get the following error:
```
failed to load config from /var/www/html/config/build/vite.config.ts
error during build:
TypeError: viteCompress is not a function
```

**Comment by aleclarson** [comment]
Check the `node_modules/vite-plugin-compress/dist/plugin.js` file and you should see `exports.default =` somewhere.

This is likely a Vite issue.

**Comment by Drumpy** [comment]
I'm having the same problem. How can we solve it? I'm using Vite v3

**Comment by acalvino4** [comment]
I've been experiencing this with other vite plugins, so I'm pretty sure @aleclarson is correct, that this is an issue with a recent vite update.

**Comment by mattjennings** [comment]
Not sure why it's happening, but for now this should work:

```js
import compress from 'vite-plugin-compress'

export default {
  plugins: [
    compress.default(),
  ]
}
```
