### ISSUE TITLE
how can the files be served with the correct content-encoding?

### ISSUE THREAD

**Issue by tve** [alloc/vite-plugin-compress#6]
I'm probably completely lost, but... using vite-plugin-compress on a vite/vue2 project I end up with compressed files in dist/assets that all have the plain file extensions, e.g. `.js`, `.css`, etc. But as far as I understand these files need to be served with a `content-encoding: br` header? How is my static file web server supposed to know which of the `.js` files are compressed and which are not? I was expecting to see a `.br` filename extension or something like that...

**Comment by aleclarson** [comment]
I would ensure all `.js` and `.css` files are compressed, then tell my web server to append the `content-encoding` header for those file extensions.
